### ISSUE TITLE
Document how to start/stop development server

### ISSUE THREAD

**Issue by pelme** [pytest-dev/blog.pytest.org#6]

**Comment by pelme** [comment]
It is documented in the README and I have verified that the instructions work as expected!

**Comment by nicoddemus** [comment]
Cool, thanks for your work on this! :smile:

I assume the blog will be published at http://blog.pytest.org, correct?

**Comment by pelme** [comment]
That's the plan! We discussed starting a pytest blog a bit at EuroPython and this is the effort to get it going. The goal is to have a community driven blog with posts from pytest developers and users.  :)

I want to get a few more basics working, I will then draft an introduction post and post to pytest-dev for feedback.
